# Enable or Disable any feature here.
# ----------------------------------------------------------------
# REQUIRES SERVER RESTART TO TAKE EFFECT

features:
  enable-walk: true




# Enter a value between 1 and 10. Default will be 6.
# Any value over 10 will increase walking speed from normal.
walking-speed: 6.0