name: RPCore
version: '${version}'
main: com.github.smittybyrd.rpcore.RPCore
paperPluginLoader: com.github.smittybyrd.rpcore.RPCoreLoader
api-version: '1.21.11'
load: POSTWORLD

softdepend:
  - [MiniMessage]

permissions:
  rpcore.walk:
    description: "Allows use of the /walk command"
    default: op
  rpcore.admin:
    description: "Admin commands"
    default: op

commands:
  walk:
    description: "Allows a player to walk at a slower speed"
    usage: /walk
    aliases: w
    permission: rpcore.walk
    permission-message: "You do not have permission to use this command!"
  rpcore:
    description: "The RPCore admin commands"
    usage: /rpcore
    aliases: rpc
    permission: rpcore.admin
    permission-message: "You do not have permission to use this command!"
